### PR TITLE
Add cgroup utility functions

### PR DESCRIPTION
**Pull request by mnagy**
These will be used by https://github.com/openshift/sti-ruby/pull/96

Trello: https://trello.com/c/kvzlecgq/853-5-tune-ruby-based-on-memory-limits-evg

### CODE REVIEW

**Comment by mnagy** [comment]
@mfojtik @bparees 

@rhcarvalho maybe for python review? :)

**Comment by mnagy** [comment]
The test fail doesn't appear to be my fault.

**Comment by mfojtik** [comment]
LGTM

**Comment by bparees** [comment]
the failure is what i brought up on scrum this morning.  not going to merge this until we can confirm it passes though.

**Comment by bparees** [comment]
[test]

**Comment by rhcarvalho** [comment]
Just so that we share a common context, the decision we made with reading cgroups to limit the container started in a build process is that if we cannot read the limits, we error out and the build will fail.

Possibly here we have different constraints I'd like to learn. What's the guarantee we want to provide for callers of this script?

If we cannot read any one of the cgroup files, we're silently ignoring the error and omitting a env var in the output. What are callers supposed to do when a var is missing?

**Comment by mfojtik** [comment]
@rhcarvalho callers shoud fallback to "default" configuration (iow. use the default values for all tuning flags). @mnagy this should be done for ruby as well.. if we don't have env vars in place, we should skip the tuning.

**Comment by bparees** [comment]
@mfojtik +1

**Pull request merged**
