### PR TITLE
Group instructions together to reduce number of layers

### PR DESCRIPTION
**Pull request by rhcarvalho**
@bparees PTAL, @mfojtik FYI no problem with keeping the comments in place :smile:

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by mfojtik** [comment]
@rhcarvalho can you build the image locally and verify `docker inspect ` Env if the values are correct (no trailing/extra whitespaces).

LGTM after quash.

**Comment by rhcarvalho** [comment]
> @rhcarvalho can you build the image locally and verify docker inspect Env if the values are correct (no trailing/extra whitespaces).

I've checked this builds correctly before sending the PR :stuck_out_tongue_winking_eye: 

And I have the experience messing around with Dockerfiles and their parsing (worked on Dockerfile rewrite code...), that's how I was sure about the possibility to interleave comments and non-comment lines.

**Comment by bparees** [comment]
needs rebase + squash

**Comment by rhcarvalho** [comment]
@bparees PTAL

**Comment by bparees** [comment]
so clean and efficient now, thanks @rhcarvalho! :)

**Pull request merged**
