### PR TITLE
Enable rhel-7-server-optional-rpms for bsdtar

### PR DESCRIPTION
**Pull request by sdodson**
I don't know if this is necessary for centos or not

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@sdodson we will see

**Comment by bparees** [comment]
what does bsdtar provide that tar isn't providing?

**Comment by mfojtik** [comment]
@bparees it makes ruby bundler happy! (or at least @jhadvig said so)

**Comment by bparees** [comment]
failure: Error getting repository data for rhel-7-server-optional-rpms, repository not found

**Comment by bparees** [comment]
"yum-config-manager --enable rhel-7-server-optional-rpms" is how we do this in our other images:
https://github.com/openshift/mongodb/blob/master/2.4/Dockerfile.rhel7#L36

**Comment by sdodson** [comment]
Switched to using yum-config-manager. Though I doubt that'll fix the test.

**Comment by bparees** [comment]
i'm confused.:
https://github.com/openshift/sti-base/blob/master/Dockerfile.rhel7#L74

https://github.com/openshift/sti-base/pull/66/files#diff-b0556bed298b3a4fb269eb10d69c91a5L75

i don't see why it should matter, but do a rebase?

**Pull request merged**
