### PR TITLE
Add gd-devel, needed for jpeg support in various downstream image frameworks

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/sti-perl/issues/68
fixes https://github.com/openshift/sti-python/issues/103

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
let's see if the repo gods are in a better mood today.
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Pull request merged**
