### PR TITLE
Enable SCL globally without sourcing bashrc

### PR DESCRIPTION
**Pull request by mfojtik**
This PR enables the SCL collections globally by using BASH_ENV to inject the `scl enable` to every `/bin/bash` session.

This require change to every image we have, so don't merge it on its own, this have to be merged together with other PR's I will link to this PR.

### CODE REVIEW

**Comment by mfojtik** [comment]
FYI: The tests will fail for all those images without the change in sti-base. I'm testing all PR's manually using make test.

**Comment by mfojtik** [comment]
@bparees @mnagy @rhcarvalho @soltysh @jhadvig guys, can I ask you to just double-check if I didn't miss something in all this copy & pasting? I ran `make test` for every repo we have with success.

Also I just want to make you aware of this change. This means that we no longer need to source `.bashrc` in any script and the SCL should be enabled automatically in every bash session.

@hhorak can you please confirm that using BASH_ENV this way won't break anything? So far all our tests are passing (including the full examples we have in openshift org).

**Comment by mnagy** [comment]
LGTM

**Comment by rhcarvalho** [comment]
LGTM, love the SKIP_SQUASH.

**Comment by mfojtik** [comment]
I should probably put a fat warning to every .bashrc saying that you should NOT add more stuff there as it will be run everytime you execute the bash itself. This can be nasty and for example in sti-python we do the arbitrary user magic in that file. This magic will be execute everytime you run bash. We should probably move that into separate file and source it just in `run` script as I think that it is the only place where we do care about setting the arbitrary user.

**Comment by mfojtik** [comment]
(warning added), got 2 lgtm, merging this.

**Comment by soltysh** [comment]
Nicely done @mfojtik !

**Pull request merged**
