### PR TITLE
[DO_NOT_MERGE] Use io.openshift.s2i.scripts-url label format

### PR DESCRIPTION
**Pull request by mfojtik**
Pending this PR to be merged: https://github.com/openshift/source-to-image/pull/220

### CODE REVIEW

**Comment by mfojtik** [comment]
https://github.com/openshift/sti-base/issues/50

**Comment by bparees** [comment]
why is this pending the S2I update?  S2I should support this image as is since it has both labels.

**Comment by mfojtik** [comment]
@bparees right, it is not pending... s2i support both.

**Comment by bparees** [comment]
however it is failing the merge test :)

**Comment by mfojtik** [comment]
@bparees it smells like a mirror problem :/

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees I retested this and all tests are green in Jenkins... however it failed to talk to AWS in the end which marks it as a failure.... Since this change is just labels, I would vote for merging this as it is.

**Comment by bparees** [comment]
rebuilding: https://ci.openshift.redhat.com/jenkins/job/sti-base/79/

**Pull request merged**
