### PR TITLE
Rename /opt/openshift to opt/app-root 

### PR DESCRIPTION
**Pull request by humaton**
https://github.com/sclorg/rhscl2dockerfile/issues/29

### CODE REVIEW

**Comment by jhadvig** [comment]
@humaton can you also update the path in the `base-usage` file.
https://github.com/openshift/sti-base/blob/master/bin/base-usage#L19

**Comment by mfojtik** [comment]
[test]

**Comment by humaton** [comment]
Sorry guys but I would not write tests in bash.

**Comment by mfojtik** [comment]
@humaton don't worry, I'm just using this PR as canary to test Jenkins ;-)

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
[test]

**Comment by jhadvig** [comment]
@humaton pls squash it into one commit, no point to have two separate commits with the same change.

**Comment by jhadvig** [comment]
LGTM

**Comment by mfojtik** [comment]
I would want to test all images before we merge this change so we know if we're broken or not.

**Comment by jhadvig** [comment]
@mfojtik +1
will manually test this change in all our images

**Comment by jhadvig** [comment]
@bparees @mfojtik I've applied and tested(manually) the change on all our sti images and it worked. Since that I've opened PR for sti-ruby,python,perl,php
Will also test the change on *-ex apps so we are safe on this change, since this is a pretty big change.

**Comment by bparees** [comment]
:+1: thanks @jhadvig -ex testing is a very good idea

**Comment by jhadvig** [comment]
Tested this change with all our sti images + rails/dancer/django-ex
Everything went without problem. Lets merge it :)

**Pull request merged**
